### PR TITLE
Update to 6.3.2

### PR DESCRIPTION
**Pull request by THS-on**
### Changes
 - Upstream now supports running the agent as non-root by dropping privileges after startup. I switched to that instead of using our solution.
 -  Removed m2crypto an simplejson as a dependency because they are no longer needed.

I have no idea why the "New upstream version 6.3.1" commit is not the same as the one in master...

Also removing the name in the changelog makes `gbp dch -aR` unhappy.

### CODE REVIEW

**Comment by THS-on** [comment]
@utkarsh2102 with the permission "hack" for the agent now removed, do you think we can try bring this package into Debian?

**Comment by THS-on** [comment]
@utkarsh2102 friendly ping :)

**Review by utkarsh2102 — APPROVED** [review]
This looks good! At least the `debian/` ones certainly look fine to me. Quick request: can you test this on Ubuntu 18.04/20.04 really quickly? If everything works, we can have this merged and we'll see the Debian bits accordingly. What do you think? Let me know!

**Comment by THS-on** [comment]
I've tested on 20.04 and it works as expected. For 18.04 a newer Tornado version (>= 5.X) is required for the verifier as already noted in the last PR, but the agent works.

**Comment by THS-on** [comment]
@utkarsh2102 6.4.0 is now out, but I think we should merge this first. 

For 6.4.0 we will require Lark (https://lark-parser.readthedocs.io/en/latest/) which is in 20.04 but not in 18.04. Can you add that to your PPA and also add a newer version of Tornado?

**Comment by utkarsh2102** [comment]
> For 6.4.0 we will require Lark (https://lark-parser.readthedocs.io/en/latest/) which is in 20.04 but not in 18.04. Can you add that to your PPA and also add a newer version of Tornado?

Aaah, okay. I'll do it when I get time. But we can keep things updated here, I think!

**Comment by utkarsh2102** [comment]
Also, thank youuuuuuuuuuuuuuuu for your work! \o/

**Pull request merged**
