### PR TITLE
Move sqlalchemy and alembic to -server

### PR DESCRIPTION
**Pull request by utkarsh2102**
Closes: #25

### CODE REVIEW

**Comment by mirespace** [comment]
IIUC the target of this PR, If we don't care about what agents needs, because it needs the -lib package:

```
root@bionic-keylime:~/Code/Builds# apt depends python3-keylime-agent
python3-keylime-agent
  Depends: adduser
  Depends: python3
  Depends: python3-keylime-lib
  Depends: <python3:any>
    python3
  Recommends: python3-keylime-doc
  Suggests: python3-keylime-defaultconf
```
I suppose we can remove them from there. If not, the lib package would need to be split (one for server, one for agent, I guess...).

**Review by THS-on — APPROVED** [review]
Tested that the agent still starts correctly is alembic and sqlalchemy are not installed.

**Comment by utkarsh2102** [comment]
@THS-on, I pushed a fix again, could you re-review, please? Should be simple, though.

**Comment by THS-on** [comment]
@utkarsh2102 the tenant should not need alembic or sqlalchemy. What breaks if we remove the dependency there?

**Comment by utkarsh2102** [comment]
> @utkarsh2102 the tenant should not need alembic or sqlalchemy. What breaks if we remove the dependency there?

Oh, really? I wasn't sure how tenant works and whether it'd need these two, so I let it be there. Nothing breaks if tenant doesn't need it. I've removed it again. Seems okay now?

**Comment by THS-on** [comment]
@utkarsh2102  yes looks fine.

@mirespace the main issue is that the Keylime code base as no strict separation between agent, verifier, registrar and tenant. 
Most dependencies are required by all parts of Keylime and we just move the dependencies to the specific packages where we know for sure that they are not required by the other parts.

**Pull request merged**
