### PR TITLE
Update v6.2.0

### PR DESCRIPTION
**Pull request by THS-on**
6.2.0 includes the new versioned API and incremental IMA attestation. 

Full changelog can be found here: https://github.com/keylime/keylime/releases/tag/v6.2.0

### CODE REVIEW

**Review by utkarsh2102 — APPROVED** [review]
Thank you! Can you please also push the `upstream` and `pristine-tar` branch directly?

**Comment by utkarsh2102** [comment]
Jeez, I disable this semantic-release workflow in this repository :3 
It commented on every PR! 🤦🏻‍♂️

**Comment by THS-on** [comment]
> Thank you! Can you please also push the upstream and pristine-tar branch directly?

Done. Please check if I have done it correctly this was my first time using pristine-tar.

> Jeez, I disabled this semantic-release workflow in this repository :3
> It commented on every PR! 🤦🏻‍♂️

You should also probably delete the docker images created and just disable all GitHub actions

**Comment by utkarsh2102** [comment]
> Done. Please check if I have done it correctly this was my first time using pristine-tar.

Awesome, looks all good! Thank you!
If it helps, here's my workflow for new upstream releases:
- `gbp import-orig --pristine-tar --uscan` (this shall fetch the latest g/h release)
- Press enter if you're happy w the version number (which is usually correct)
- ...and done! Just generate the d/changelog entry via `gbp dch -aR` (and build the package...)

> You should also probably delete the docker images created and just disable all GitHub actions

Ugh, I don't know how to delete those docker images, I can't see any option to. I even went through the GitHub docs but the UI is v different now. Probably you have the rights as well, can you see if you can delete them?

Either way, I have disabled all the workflows now so it won't bite us in the future (...unless they add something evil :P).

**Comment by THS-on** [comment]
> Ugh, I don't know how to delete those docker images, I can't see any option to. I even went through the GitHub docs but the UI is v different now. Probably you have the rights as well, can you see if you can delete them?

If you go to https://github.com/utkarsh2102/python-keylime/pkgs/container/python-keylime%2Fkeylime_registrar there should be on the right the option "Package settings". This opens the settings page for that image and there is a delete option.

**Comment by utkarsh2102** [comment]
> If you go to https://github.com/utkarsh2102/python-keylime/pkgs/container/python-keylime%2Fkeylime_registrar there should be on the right the option "Package settings". This opens the settings page for that image and there is a delete option.

Bah, if only I had scrolled down..
Thank you, Thore, I've deleted all of them now! \o/

**Pull request merged**
