### PR TITLE
Changes for 6.3

### PR DESCRIPTION
**Pull request by THS-on**
Here are the required changes to build Keylime 6.3.0 successfully.

Note that we require currently this patch to run without root privileges:
https://github.com/keylime/keylime/pull/857

Keylime uses SHA1 as TPM hash algorithm by default, so IMA does not break on kernel versions older than 5.10. 
We can change the default to SHA256 if all of our users use at least kernel version 5.10.

@utkarsh2102 should I put those changes in one PR next time?

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Hiya. Before I get to this PR, could you please test Ubuntu Bionic (16.04) and Focal (18.04) to make sure that this build and work fine there?

**Comment by THS-on** [comment]
I can do that, but I don't currently have a test setup for that, so this will take a little but longer. Are the required packages if they are not found in the older Ubuntu versions in your PPA?

**Comment by THS-on** [comment]
I've already validated the patches on Debian 11.

**Comment by utkarsh2102** [comment]
> I can do that, but I don't currently have a test setup for that, so this will take a little but longer.

No problem and no rush, I guess. But if we're gonna get this in, let's get it right, too! ;)

> Are the required packages if they are not found in the older Ubuntu versions in your PPA?

Yep, I think so. This PPA has mostly everything: https://launchpad.net/~utkarsh/+archive/ubuntu/keylime. Let me know if you find something missing.

**Comment by THS-on** [comment]
I'm currently waiting for 6.3.1 to be released because this fixes some issues also with Python 3.6 and the patch that I've attached to this PR.

**Pull request closed without merging**
